### ISSUE TITLE
Error: eventTask 'Busboy.addListener:finish': can not transition to 'running'

### ISSUE THREAD

**Issue by mariohmol** [mscdex/busboy#166]
Hi there!

I'm using multer module and I got into an error that seems to be related with busboy.

Check it out: https://github.com/expressjs/multer/issues/584

Any ideas on how i can solved that is appreciatted =)

Thanks

**Comment by mscdex** [comment]
This error is not coming from `busboy`, but instead `zone.js`. All that's happening here is that the `busboy` instance is emitting `'finish'`. I don't see what's wrong with that?

**Comment by mariohmol** [comment]
Is this throwing any error? or is multer that is expecting something different and throws an error? The thing is.. the nodejs breaks and i have to restart when i receive this message..  @LinusU check it out

**Comment by mariohmol** [comment]
This is the full stack:  

``` 
{
  "date": "Mon May 07 2018 09:57:24 GMT-0300 (-03)",
  "process": {
    "pid": 1571,
    "uid": 501,
    "gid": 20,
    "cwd": "/v2/web",
    "execPath": "/usr/local/bin/node",
    "version": "v6.11.2",
    "argv": [
      "/usr/local/bin/node",
      "/v2/web/dist-server/index.js"
    ],
    "memoryUsage": {
      "rss": 67952640,
      "heapTotal": 155877376,
      "heapUsed": 142088976,
      "external": 18900817
    }
  },
  "os": {
    "loadavg": [
      3.2021484375,
      3.22265625,
      3.5693359375
    ],
    "uptime": 5316
  },
  "trace": [
    {
      "column": null,
      "file": null,
      "function": "new Error",
      "line": null,
      "method": null,
      "native": true
    },
    {
      "column": null,
      "file": null,
      "function": "ZoneTask._transitionTo (/v2/web/node_modules/zone.js/dist/zone-node.js:495:23)",
      "line": null,
      "method": "_transitionTo (/v2/web/node_modules/zone.js/dist/zone-node.js:495:23)",
      "native": false
    },
    {
      "column": null,
      "file": null,
      "function": "Zone.runTask (/v2/web/node_modules/zone.js/dist/zone-node.js:155:34)",
      "line": null,
      "method": "runTask (/v2/web/node_modules/zone.js/dist/zone-node.js:155:34)",
      "native": false
    },
    {
      "column": null,
      "file": null,
      "function": "Busboy.ZoneTask.invoke (/v2/web/node_modules/zone.js/dist/zone-node.js:460:38)",
      "line": null,
      "method": "ZoneTask.invoke (/v2/web/node_modules/zone.js/dist/zone-node.js:460:38)",
      "native": false
    },
    {
      "column": null,
      "file": null,
      "function": "emitNone (events.js:91:20)",
      "line": null,
      "method": "js:91:20)",
      "native": false
    },
    {
      "column": null,
      "file": null,
      "function": "Busboy.emit (events.js:185:7)",
      "line": null,
      "method": "emit (events.js:185:7)",
      "native": false
    },
    {
      "column": null,
      "file": null,
      "function": "Busboy.emit (/v2/web/node_modules/busboy/lib/main.js:38:33)",
      "line": null,
      "method": "emit (/v2/web/node_modules/busboy/lib/main.js:38:33)",
      "native": false
    },
    {
      "column": null,
      "file": null,
      "function": "/v2/web/node_modules/busboy/lib/types/multipart.js:52:13",
      "line": null,
      "method": "js:52:13",
      "native": false
    },
    {
      "column": null,
      "file": null,
      "function": "data.args.(anonymous function) (/v2/web/node_modules/zone.js/dist/zone-node.js:1598:25)",
      "line": null,
      "method": "args.(anonymous function) (/v2/web/node_modules/zone.js/dist/zone-node.js:1598:25)",
      "native": false
    },
    {
      "column": null,
      "file": null,
      "function": "_combinedTickCallback (internal/process/next_tick.js:73:7)",
      "line": null,
      "method": "js:73:7)",
      "native": false
    },
    {
      "column": null,
      "file": null,
      "function": "process._tickCallback (internal/process/next_tick.js:104:9)",
      "line": null,
      "method": "_tickCallback (internal/process/next_tick.js:104:9)",
      "native": false
    }
  ],
  "stack": [
    "Error: eventTask 'Busboy.addListener:finish': can not transition to 'running', expecting state 'scheduled', was 'notScheduled'.",
    "    at new Error (native)",
    "    at ZoneTask._transitionTo (/v2/web/node_modules/zone.js/dist/zone-node.js:495:23) [<root>]",
    "    at Zone.runTask (/v2/web/node_modules/zone.js/dist/zone-node.js:155:34) [<root>]",
    "    at Busboy.ZoneTask.invoke (/v2/web/node_modules/zone.js/dist/zone-node.js:460:38) [<root>]",
    "    at emitNone (events.js:91:20) [<root>]",
    "    at Busboy.emit (events.js:185:7) [<root>]",
    "    at Busboy.emit (/v2/web/node_modules/busboy/lib/main.js:38:33) [<root>]",
    "    at /v2/web/node_modules/busboy/lib/types/multipart.js:52:13 [<root>]",
    "    at data.args.(anonymous function) (/v2/web/node_modules/zone.js/dist/zone-node.js:1598:25) [<root>]",
    "    at _combinedTickCallback (internal/process/next_tick.js:73:7) [<root>]",
    "    at process._tickCallback (internal/process/next_tick.js:104:9) [<root>]"
  ],
  "level": "error",
  "message": "uncaughtException: eventTask 'Busboy.addListener:finish': cannot transition to 'running', expecting state 'scheduled', was 'notScheduled'."
}
```

**Comment by mscdex** [comment]
I'd suggest try removing `zone.js` and see what happens.

**Comment by mariohmol** [comment]
I had a zone in index.js, after i removed i received this error:

``` 
/v2/web/node_modules/zone.js/dist/zone-node.js:495
                throw new Error(this.type + " '" + this.source + "': can not transition to '" + toState + "', expecting state '" + fromState1 + "'" + (fromState2 ?
                      ^
Error: eventTask 'Busboy.addListener:finish': can not transition to 'running', expecting state 'scheduled', was 'notScheduled'.
    at new Error (native)
``` 

I have a SSR app, after i removed the angular app from this (as it uses zone) .. it worked

I will open an issue on zone.js as well..

thanks =)

**Comment by mariohmol** [comment]
Upgrading to "zone.js": "^0.8.26" worked! =) Thanks for your help!

**Comment by mariohmol** [comment]
Update, new zone.js is breaking mongoose, use  0.8.20 that is working for mongoose and wav files.  https://github.com/angular/zone.js/issues/1085#issuecomment-387128747
