### ISSUE TITLE
busboy@1.6.0 SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by wh0amitz** [mscdex/busboy#342]
```
root@ubuntu18:~/docker/src# node app.js
/root/docker/src/node_modules/busboy/lib/utils.js:469
    } catch {}
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/docker/src/node_modules/busboy/lib/index.js:3:30)
```

**Comment by wh0amitz** [comment]
Upgrade nodejs to 12 or above
