### ISSUE TITLE
Cannot read property 'ended' of undefined

### ISSUE THREAD

**Issue by qu1ze** [mscdex/busboy#68]
I'm getting following error:
```
TypeError: Cannot read property 'ended' of undefined
    at FileStream.Writable.write (_stream_writable.js:180:12)
    at FileStream.emit (events.js:95:17)
    at FileStream.<anonymous> (_stream_readable.js:765:14)
    at FileStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at FileStream.Readable.push (_stream_readable.js:128:10)
    at PartStream.onData (/home/oleg/bet/node_modules/busboy/lib/types/multipart.js:215:28)
    at PartStream.emit (events.js:95:17)
```

Code:
```
router.post('/api/bet/photo', function(req, res) {
  var busboy = new Busboy({ headers : req.headers });
  busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
    cloudinary.uploadStream(file, function(error, result) {
      if (error) {
        return res.send(error);
      }
      
      res.send(result);
    });   
  });
  req.pipe(busboy);    
});
```

**Comment by mscdex** [comment]
Can you provide a simple, complete test case I can use to reproduce the problem?

**Comment by qu1ze** [comment]
Problem is solved. Misunderstood the issue, solution is simple, just need to downgrade cloudinary lib from 1.1.1 to 1.0.10.
